// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuvy_8Dur7l7E7FiWfj_vYmfcmf0ysTpc',
    appId: '1:497292669936:web:619156cc03bbe9e53fa335',
    messagingSenderId: '497292669936',
    projectId: 'doaa-39b5a',
    authDomain: 'doaa-39b5a.firebaseapp.com',
    storageBucket: 'doaa-39b5a.appspot.com',
    measurementId: 'G-7YPSZ3FJLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp8XmP54hotKRwLqT9hmN6xB9Sq7Eu1Ag',
    appId: '1:497292669936:android:857393b989b3e56b3fa335',
    messagingSenderId: '497292669936',
    projectId: 'doaa-39b5a',
    storageBucket: 'doaa-39b5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUoSbJxAZugk7oksixx4yvt-uOhvSkgE',
    appId: '1:497292669936:ios:cd96fad3c28e294a3fa335',
    messagingSenderId: '497292669936',
    projectId: 'doaa-39b5a',
    storageBucket: 'doaa-39b5a.appspot.com',
    iosClientId: '497292669936-vscfbsumifjbp5j4iomllfbtpt03fjcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNUoSbJxAZugk7oksixx4yvt-uOhvSkgE',
    appId: '1:497292669936:ios:cd96fad3c28e294a3fa335',
    messagingSenderId: '497292669936',
    projectId: 'doaa-39b5a',
    storageBucket: 'doaa-39b5a.appspot.com',
    iosClientId: '497292669936-vscfbsumifjbp5j4iomllfbtpt03fjcn.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranapi',
  );
}
